import P1 from "../assets/images/Slider/Slider1.jpg";
import P2 from "../assets/images/Slider/Slider2.jpg";
import P3 from "../assets/images/Slider/Slider3.jpg";

export const products = [
  {
    id: 1,
    name: "کرم آبرسان",
    description: "<p>این کرم پوست شما را لطیف و شاداب می‌کند.</p>",
    price: 120000,
    newPrice: 95000,
    image: P1,
    category: "پوستی",
    onSale: true,
  },
  {
    id: 2,
    name: "رژ لب مات",
    description: "<p>دارای ماندگاری بالا و رنگ طبیعی.</p>",
    price: 180000,
    newPrice: null,
    image: P2,
    category: "آرایشی",
    onSale: false,
  },
  {
    id: 3,
    name: "کرم ضد آفتاب",
    description: "<p>محافظت کامل در برابر اشعه UV.</p>",
    price: 150000,
    newPrice: 120000,
    image: P3,
    category: "پوستی",
    onSale: true,
  },
  {
    id: 4,
    name: "کرم ضد آفتاب",
    description: "<p>محافظت کامل در برابر اشعه UV.</p>",
    price: 150000,
    newPrice: 120000,
    image: P3,
    category: "پوستی",
    onSale: false,
  },
  {
    id: 5,
    name: "کرم ضد آفتاب",
    description: "<p>محافظت کامل در برابر اشعه UV.</p>",
    price: 150000,
    newPrice: 120000,
    image: P3,
    category: "پوستی",
    onSale: true,
  },
  {
    id: 6,
    name: "کرم ضد آفتاب",
    description: "<p>محافظت کامل در برابر اشعه UV.</p>",
    price: 150000,
    newPrice: 120000,
    image: P3,
    category: "پوستی",
    onSale: false,
  },
  {
    id: 7,
    name: "کرم ضد آفتاب",
    description: "<p>محافظت کامل در برابر اشعه UV.</p>",
    price: 150000,
    newPrice: 120000,
    image: P3,
    category: "پوستی",
    onSale: true,
  },
  {
    id: 8,
    name: "کرم آبرسان",
    description: "<p>این کرم پوست شما را لطیف و شاداب می‌کند.</p>",
    price: 120000,
    newPrice: 95000,
    image: P1,
    category: "پوستی",
    onSale: true,
  },
  {
    id: 9,
    name: "رژ لب مات",
    description: "<p>دارای ماندگاری بالا و رنگ طبیعی.</p>",
    price: 180000,
    newPrice: null,
    image: P2,
    category: "آرایشی",
    onSale: false,
  },
  {
    id: 10,
    name: "کرم آبرسان",
    description: "<p>این کرم پوست شما را لطیف و شاداب می‌کند.</p>",
    price: 120000,
    newPrice: 95000,
    image: P1,
    category: "پوستی",
    onSale: true,
  },
  {
    id: 11,
    name: "رژ لب مات",
    description: "<p>دارای ماندگاری بالا و رنگ طبیعی.</p>",
    price: 180000,
    newPrice: null,
    image: P2,
    category: "آرایشی",
    onSale: false,
  },
];
